# Generated by Django 3.2.25 on 2025-01-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tecnologias', models.ManyToManyField(blank=True, null=True, related_name='programadores', to='tecnologias.Tecnologia')),
            ],
        ),
    ]
