# Generated by Django 3.2.25 on 2025-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0001_initial'),
        ('programadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='programadores', to='tecnologias.Tecnologia'),
        ),
    ]
